services:
  back:
    build: photoprocatServer/.
    ports:
      - "5200:5200"

  front:
    build: 
      context: photoprocatClient/.
    labels:
      SERVICE_CHECK_INTERVAL: 10s
    ports:
      - "3000:80"
    depends_on:
      - back


